# 元信息表
[meta]
title = "78张塔罗牌+简单牌阵"
author = "Entropy"
version = "1.0"
license = "CC-BY-NC-SA 4.0"
date = 2024-04-19
update_date = 2024-04-19
desc = "包含22张大阿卡那和56张小阿卡那的全套韦特塔罗牌正逆位释义，以及简单牌阵。塔罗牌释义来自Labyrinthos.co以及个人理解。支持单独抽取大阿卡那牌。牌阵包含：单张塔罗牌，三张塔罗牌，凯尔特十字。三张塔罗牌可用于过去/现在/未来，现状/行为/结果，身/心/灵等多种解读。抽牌阵时可能会同时抽到一张牌的正位和逆位，出现这种情况建议重新抽。"

# 牌组表
[decks]
"__单张塔罗牌" = [
  "0.愚者(The Fool)，正位。新的开始，自由，冒险，理想主义，天真无邪，未来的无限可能。",
  "0.愚者(The Fool)，逆位。天真，愚蠢，鲁莽，被利用，考虑不周，注意力分散。",
  "I.魔术师(The Magician)，正位。意志力，强大的能力，技巧，资源充沛，精神集中，无限可能。",
  "I.魔术师(The Magician)，逆位。欺骗，狡诈，诡计，浪费的天赋，幻象。",
  "II.女祭司(The High Priestess)，正位。无意识，直觉，灵性，高层次的力量，遵循内心的声音。",
  "II.女祭司(The High Priestess)，逆位。被压抑的直觉，隐藏的动机，肤浅，迷惑，认知失调。",
  "III.女皇(The Empress)，正位。神圣的女性，官能，丰饶，呵护，抚育，创造力，美丽，自然，富足。",
  "III.女皇(The Empress)，逆位。不安，忽视，强势，令人窒息的关心，缺少成长，缺少进步，沉闷。",
  "IV.皇帝(The Emperor)，正位。稳定，有结构，保护，权威，统治，掌控，实践，精神集中，纪律。",
  "IV.皇帝(The Emperor)，逆位。暴君，专横，死板，固执，缺少纪律，鲁莽，不稳定的权力关系，缺乏控制力，官僚主义。",
  "V.教皇(The Hierophant)，正位。传统，社会团体，保守主义，从众，教育，知识，信仰。",
  "V.教皇(The Hierophant)，逆位。叛逆，反抗，反传统，独树一帜，忽视，失控，新的方案。",
  "VI.恋人(The Lovers)，正位。爱，联合，伙伴，情感关系，选择，浪漫，平衡，协同，和谐。",
  "VI.恋人(The Lovers)，逆位。不和谐，失衡，冲突，分离，冷淡，不好的选择，犹豫不定，缺乏或无效沟通，逃避责任。",
  "VII.战车(The Chariot)，正位。成功，野心，决心，意志力，控制力，自律，精神集中，克服困难。",
  "VII.战车(The Chariot)，逆位。强行，漫无方向，失控，无力，侵略性，障碍，意志不坚，执迷不悟，缺乏动机。",
  "VIII.力量(Strength)，正位。勇气，自信，同情心，决心，坚韧，冷静，自控。",
  "VIII.力量(Strength)，逆位。自我怀疑，弱点，低自信，不足，懦弱，愤怒，恐惧，抑郁，嫉妒，不安。",
  "IX.隐者(The Hermit)，正位。自省，沉思，独处，远离尘世，探寻自我，导师。",
  "IX.隐者(The Hermit)，逆位。寂寞，孤立，离群索居，社交恐惧，冷淡，回归社会。",
  "X.命运之轮(The Wheel of Fortune)，正位。变化，轮回，命运，重要时刻，好运，意外事件，机遇。",
  "X.命运之轮(The Wheel of Fortune)，逆位。厄运，失控，不好的变化，延迟，不适应。",
  "XI.正义(Justice)，正位。正义，报应，后果，责任，法律，真相，诚实，正直，因果。",
  "XI.正义(Justice)，逆位。不正义，惩罚，谎言，腐败，不公，逃避责任。",
  "XII.倒吊人(The Hanged Man)，正位。牺牲，等待，悬而未定，缺少方向，转换视角，沉思，智慧。",
  "XII.倒吊人(The Hanged Man)，逆位。拖延，不感兴趣，停滞，拒绝牺牲，僵局，冷漠，无谓的牺牲。",
  "XIII.死亡(Death)，正位。终局，改变，放手，断舍离，轮回，新生。",
  "XIII.死亡(Death)，逆位。惧怕改变，重蹈覆辙，抗拒改变，停滞，腐败。",
  "XIV.节制(Temperance)，正位。平衡，耐心，中庸，冷静，和谐，安宁，克己。",
  "XIV.节制(Temperance)，逆位。失衡，冗余，极端，不和谐，鲁莽，匆忙，焦虑。",
  "XV.恶魔(The Devil)，正位。对立，成瘾，偏执，依赖，过度，无力，困境，空虚，纵欲，享乐主义，失控，自毁。",
  "XV.恶魔(The Devil)，逆位。独立，自由，启示，释放，重寻力量，重获控制，克服困难。",
  "XVI.塔(The Tower)，正位。灾难，毁灭，倾覆，创伤，巨变，混沌。",
  "XVI.塔(The Tower)，逆位。避免灾难，苟延残喘，抗拒改变，近在眼前的灾难，生还。",
  "XVII.星星(The Stars)，正位。希望，灵感，乐观，信念，重生，治愈，精神焕发。",
  "XVII.星星(The Stars)，逆位。绝望，失落，悲观，缺乏信念，沮丧，不自信，缺乏动力，缺乏热情。",
  "XVIII.月亮(The Moon)，正位。幻象，直觉，不确定，迷惑，复杂，秘密，潜意识，神秘，隐藏的真相。",
  "XVIII.月亮(The Moon)，逆位。恐惧，欺骗，焦虑，误会，曲解，恐惧，识破幻觉，清晰。",
  "XIX.太阳(The Sun)，正位。幸福，成功，乐观，生命力，快乐，自信，真相，富饶，光明，热情。",
  "XIX.太阳(The Sun)，逆位。被阻碍的幸福，过度热情，悲观，不切实际，自负，过度乐观，无趣。",
  "XX.审判(Judgement)，正位。自省，觉醒，新生，目的，思索，承认。",
  "XX.审判(Judgement)，逆位。自我怀疑，对自我认知不明，不长进，自我厌恶",
  "XXI.世界(The World)，正位。完整，完美，归属感，和谐，成就，满足，涅槃。",
  "XXI.世界(The World)，逆位。未完成，无果，缺失感，空虚。",
  "权杖1，正位。灵感，创造力，新的动力，热情，能量。",
  "权杖1，逆位。拖延，瓶颈，缺乏热情，缺乏能量，迟疑，灵感枯竭。",
  "权杖2，正位。计划，做决定，脱离舒适圈，冒险，进步，探索，发现。",
  "权杖2，逆位。恶劣的计划，过度思考，不采取行动，保守，避免风险。",
  "权杖3，正位。动力，自信，扩张，成长，远见，前程，机会。",
  "权杖3，逆位。限制，缺少进步，障碍，滞后，烦闷，挑战。",
  "权杖4，正位。家庭，团聚，社区，关系良好，休憩。",
  "权杖4，逆位。缺乏沟通，不稳定，亲友间的冲突。",
  "权杖5，正位。竞争，冲突，敌对，示威。",
  "权杖5，逆位。避免冲突，求同存异。",
  "权杖6，正位。胜利，受尊重，认可，公开赞誉，成就。",
  "权杖6，逆位。自我怀疑，缺少认可，惩罚。",
  "权杖7，正位。坚持立场，防御，维持控制。",
  "权杖7，逆位。放弃，自信破碎，精疲力竭。",
  "权杖8，正位。迅速的行动，进展，速战速决，快速决策，一往无前。",
  "权杖8，逆位。障碍，等候，减缓。",
  "权杖9，正位。坚韧，最后一搏，竭尽全力。",
  "权杖9，逆位。枯竭，疲惫，油尽灯枯。",
  "权杖10，正位。成就，责任，负担。",
  "权杖10，逆位。缺乏优先度，无谓的负担，无法把责任分配给他人。",
  "权杖侍从，正位。探索，激动，自由，灵感。",
  "权杖侍从，逆位。缺少方向，负能量，受限制，无计划。",
  "权杖骑士，正位。行动，冒险，无畏，将灵感化为现实，不切实际。",
  "权杖骑士，逆位。愤怒，冲动，鲁莽，不顾后果。",
  "权杖皇后，正位。勇气，魅力，领导力，坚定，内在的力量。",
  "权杖皇后，逆位。自私，嫉妒，专横，愤怒，仇恨。",
  "权杖国王，正位。大局观，领导，克服困难，远见。",
  "权杖国王，逆位。冲动，激进的目标，暴戾，强横，鲁莽，不切实际。",
  "圣杯1，正位。情感充沛，创造力，新鲜的情感。",
  "圣杯1，逆位。浪费的情感，被阻碍的创造力，空虚",
  "圣杯2，正位。联合，伙伴，合二为一，平衡的情感，能量，激情，性爱。",
  "圣杯2，逆位。不平衡，沟通破裂，紧张的关系。",
  "圣杯3，正位。友谊，社交，快乐。",
  "圣杯3，逆位。盲从，从众，独处。",
  "圣杯4，正位。冷漠，自省，解离。",
  "圣杯4，逆位。无聊，理所当然，冷漠无情。",
  "圣杯5，正位。失去，悲恸，失望，失落，残存的希望。",
  "圣杯5，逆位。接受，继续生活，找到内心的宁静，疗愈。",
  "圣杯6，正位。怀念，重逢，美好的回忆，过去与现在的交会。",
  "圣杯6，逆位。抗拒改变，执着于过去，不切实际。",
  "圣杯7，正位。众多的选择，幻想，幻象，潜藏的危机。",
  "圣杯7，逆位。诱惑，多样性，迷惑，无法理性思考。",
  "圣杯8，正位。远离，幻灭，不满足，失落，抛弃，止损。",
  "圣杯8，逆位。迷惑，畏惧未知，畏惧失去，犹豫不决。",
  "圣杯9，正位。舒适，情绪稳定，奢侈，自满，洋洋得意。",
  "圣杯9，逆位。贪婪，骄傲自大，不满足。",
  "圣杯10，正位。平静，满足，归属感，幸福。",
  "圣杯10，逆位。破碎的梦，家庭不谐，恶劣的关系，冲突。",
  "圣杯侍从，正位。惊喜，内在孩童，想象，潜意识。",
  "圣杯侍从，逆位。不成熟，逃避现实，缺乏创造力。",
  "圣杯骑士，正位。调解，化情绪为行动，浪漫，魅力，追寻完美和善的梦想。",
  "圣杯骑士，逆位。虚荣，回避冲突，阿谀奉承，迷失，情绪失控。",
  "圣杯皇后，正位。友善，冷静，平和，同情心。",
  "圣杯皇后，逆位。冷漠，不安，依赖，情绪不稳定。",
  "圣杯国王，正位。同情心，自控力，智慧，慷慨。",
  "圣杯国王，逆位。操控人心，喜怒无常，欺骗，失控。",
  "宝剑1，正位。突破，力量，思维敏锐。",
  "宝剑1，逆位。迷惑，残忍，混乱。",
  "宝剑2，正位。艰难的决定，犹豫不决，僵局。",
  "宝剑2，逆位。双输，更小的损失，没有正确答案，困惑。",
  "宝剑3，正位。心碎，折磨，绝望，背叛，孤独，牺牲。",
  "宝剑3，逆位。康复，原谅，继续前行。",
  "宝剑4，正位。休息，疗愈，康复。",
  "宝剑4，逆位。不安，疲倦，压力。",
  "宝剑5，正位。肆无忌惮的野心，不计代价的胜利，狡诈，对手的仇恨。",
  "宝剑5，逆位。长存的仇恨，希望和解，希望原谅。",
  "宝剑6，正位。过渡，抛下过往，继续前行。",
  "宝剑6，逆位。情感包袱，未解决的问题，抗拒改变。",
  "宝剑7，正位。欺瞒，狡诈，视而不见。",
  "宝剑7，逆位。改过自新，希望改变，浪子回头。",
  "宝剑8，正位。囚禁，无力，自我放逐，自认是受害者。",
  "宝剑8，逆位。悦纳自我，新的视角，自由，自省。",
  "宝剑9，正位。焦虑，绝望，梦魇。",
  "宝剑9，逆位。恐惧，缺乏客观视角，绝望。",
  "宝剑10，正位。遭受背叛，失败。",
  "宝剑10，逆位。复苏，重拾活力，不可避免的终局。",
  "宝剑侍从，正位。好奇心，不息，精神力，热情。",
  "宝剑侍从，逆位。匆忙，放空话。",
  "宝剑骑士，正位。目标，速度，野心，决心。",
  "宝剑骑士，逆位。漫无目的，不顾后果，不可预测。",
  "宝剑皇后，正位。独特视角，冷静，独立，敏锐，有条理，城府。",
  "宝剑皇后，逆位。冷血，残忍，辛辣。",
  "宝剑国王，正位。智慧，权力，荣誉，真相，冷静。",
  "宝剑国王，逆位。操控人心，残酷，批评家，冷酷无情，自私，利用他人。",
  "星币1，正位。机会，繁荣，创业。",
  "星币1，逆位。失去的机会。",
  "星币2，正位。平衡，计划，适应改变。",
  "星币2，逆位。失衡，杂乱无章，不知所措。",
  "星币3，正位。团队合作，建设，卓有成效。",
  "星币3，逆位。缺少合作，杂乱无章，人际矛盾，竞争。",
  "星币4，正位。保守，安全，节俭。",
  "星币4，逆位。贪婪，吝啬，占有欲。",
  "星币5，正位。需求，贫困，不安，艰难的时节，潜在的帮助。",
  "星币5，逆位。恢复，重新繁荣，孤立。",
  "星币6，正位。慈善，慷慨，分享，理解，同情。",
  "星币6，逆位。自私，吝啬，负债，拒绝分享。",
  "星币7，正位。认真负责，毅力，勤勉，专注。",
  "星币7，逆位。徒劳无功，注意力分散，浪费的努力，烦闷。",
  "星币8，正位。教育，学徒，成就，努力。",
  "星币8，逆位。注意力分散，没有目标，没有动力。",
  "星币9，正位。劳动果实，独立，努力后的收获，富庶。",
  "星币9，逆位。失误，工作狂，挫折，徒劳无功。",
  "星币10，正位。遗产，传承，巅峰，成就感，满足。",
  "星币10，逆位。失败，不稳定，缺乏资源，一无所获。",
  "星币侍从，正位。梦想，热情，新的机会，创业。",
  "星币侍从，逆位。白日梦，不切实际，懒惰。",
  "星币骑士，正位。努力，奉献，日复一日的劳作，效率，勤劳。",
  "星币骑士，逆位。懒惰，偏执，徒劳无功，短视。",
  "星币皇后，正位。实干，物质享受，经济稳定，家庭平和。",
  "星币皇后，逆位。生活和工作的不平衡，强横，徒劳无功。",
  "星币国王，正位。富饶，有效率，责任心，稳定，安全。",
  "星币国王，逆位。贪婪，物质享受，感官诱惑。"
  ]
"单张大阿卡那牌" = [
 "\n0.愚者(The Fool)，正位。新的开始，自由，冒险，理想主义，天真无邪，未来的无限可能。",
  "\n0.愚者(The Fool)，逆位。天真，愚蠢，鲁莽，被利用，考虑不周，注意力分散。",
  "\nI.魔术师(The Magician)，正位。意志力，强大的能力，技巧，资源充沛，精神集中，无限可能。",
  "\nI.魔术师(The Magician)，逆位。欺骗，狡诈，诡计，浪费的天赋，幻象。",
  "\nII.女祭司(The High Priestess)，正位。无意识，直觉，灵性，高层次的力量，遵循内心的声音。",
  "\nII.女祭司(The High Priestess)，逆位。被压抑的直觉，隐藏的动机，肤浅，迷惑，认知失调。",
  "\nIII.女皇(The Empress)，正位。神圣的女性，官能，丰饶，呵护，抚育，创造力，美丽，自然，富足。",
  "\nIII.女皇(The Empress)，逆位。不安，忽视，强势，令人窒息的关心，缺少成长，缺少进步，沉闷。",
  "\nIV.皇帝(The Emperor)，正位。稳定，有结构，保护，权威，统治，掌控，实践，精神集中，纪律。",
  "\nIV.皇帝(The Emperor)，逆位。暴君，专横，死板，固执，缺少纪律，鲁莽，不稳定的权力关系，缺乏控制力，官僚主义。",
  "\nV.教皇(The Hierophant)，正位。传统，社会团体，保守主义，协调一致，教育，知识，信仰。",
  "\nV.教皇(The Hierophant)，逆位。叛逆，反抗，反传统，独树一帜，忽视，失控，新的方案。",
  "\nVI.恋人(The Lovers)，正位。爱，联合，伙伴，情感关系，选择，浪漫，平衡，协同，和谐。",
  "\nVI.恋人(The Lovers)，逆位。不和谐，失衡，冲突，分离，冷淡，不好的选择，犹豫不定，缺乏或无效沟通，逃避责任。",
  "\nVII.战车(The Chariot)，正位。成功，野心，决心，意志力，控制力，自律，精神集中，克服困难。",
  "\nVII.战车(The Chariot)，逆位。强行，漫无方向，失控，无力，侵略性，障碍，意志不坚，执迷不悟，缺乏动机。",
  "\nVIII.力量(Strength)，正位。勇气，自信，同情心，决心，坚韧，冷静，自控。",
  "\nVIII.力量(Strength)，逆位。自我怀疑，弱点，低自信，不足，懦弱，愤怒，恐惧，抑郁，嫉妒，不安。",
  "\nIX.隐者(The Hermit)，正位。自省，沉思，独处，远离尘世，探寻自我，导师。",
  "\nIX.隐者(The Hermit)，逆位。寂寞，孤立，离群索居，社交恐惧，冷淡，回归社会。",
  "\nX.命运之轮(The Wheel of Fortune)，正位。变化，轮回，命运，重要时刻，好运，意外事件，机遇。",
  "\nX.命运之轮(The Wheel of Fortune)，逆位。厄运，失控，不好的变化，延迟，不适应。",
  "\nXI.正义(Justice)，正位。正义，报应，后果，责任，法律，真相，诚实，正直，因果。",
  "\nXI.正义(Justice)，逆位。不正义，惩罚，谎言，腐败，不公，逃避责任。",
  "\nXII.倒吊人(The Hanged Man)，正位。牺牲，等待，悬而未定，缺少方向，转换视角，沉思，智慧。",
  "\nXII.倒吊人(The Hanged Man)，逆位。拖延，不感兴趣，停滞，拒绝牺牲，僵局，冷漠，无谓的牺牲。",
  "\nXIII.死亡(Death)，正位。终局，改变，放手，断舍离，轮回，新生。",
  "\nXIII.死亡(Death)，逆位。惧怕改变，重蹈覆辙，抗拒改变，停滞，腐败。",
  "\nXIV.节制(Temperance)，正位。平衡，耐心，中庸，冷静，和谐，安宁，克己。",
  "\nXIV.节制(Temperance)，逆位。失衡，冗余，极端，不和谐，鲁莽，匆忙，焦虑。",
  "\nXV.恶魔(The Devil)，正位。对立，成瘾，偏执，依赖，过度，无力，困境，空虚，纵欲，享乐主义，失控，自毁。",
  "\nXV.恶魔(The Devil)，逆位。独立，自由，启示，释放，重寻力量，重获控制，克服困难。",
  "\nXVI.塔(The Tower)，正位。灾难，毁灭，倾覆，创伤，巨变，混沌。",
  "\nXVI.塔(The Tower)，逆位。避免灾难，苟延残喘，抗拒改变，近在眼前的灾难，生还。",
  "\nXVII.星星(The Stars)，正位。希望，灵感，乐观，信念，重生，治愈，精神焕发。",
  "\nXVII.星星(The Stars)，逆位。绝望，失落，悲观，缺乏信念，沮丧，不自信，缺乏动力，缺乏热情。",
  "\nXVIII.月亮(The Moon)，正位。幻象，直觉，不确定，迷惑，复杂，秘密，潜意识，神秘，隐藏的真相。",
  "\nXVIII.月亮(The Moon)，逆位。恐惧，欺骗，焦虑，误会，曲解，恐惧，识破幻觉，清晰。",
  "\nXIX.太阳(The Sun)，正位。幸福，成功，乐观，生命力，快乐，自信，真相，富饶，光明，热情。",
  "\nXIX.太阳(The Sun)，逆位。被阻碍的幸福，过度热情，悲观，不切实际，自负，过度乐观，无趣。",
  "\nXX.审判(Judgement)，正位。自省，觉醒，新生，目的，思索，承认。",
  "\nXX.审判(Judgement)，逆位。自我怀疑，对自我认知不明，不长进，自我厌恶",
  "\nXXI.世界(The World)，正位。完整，完美，归属感，和谐，成就，满足，涅槃。",
  "\nXXI.世界(The World)，逆位。未完成，无果，缺失感，空虚。"
]
"单张塔罗牌" = [
"\n{__单张塔罗牌}"
]
"三张塔罗牌" = [
"""\n
1.{__单张塔罗牌}
2.{__单张塔罗牌}
3.{__单张塔罗牌}
"""
]
"凯尔特十字" = [
"""\n
1.问题的核心：{__单张塔罗牌}
2.挑战：{__单张塔罗牌}
3.潜意识：{__单张塔罗牌}
4.过去：{__单张塔罗牌}
5.表意识：{__单张塔罗牌}
6.未来：{__单张塔罗牌}
7.自身：{__单张塔罗牌}
8.环境：{__单张塔罗牌}
9.希望和恐惧：{__单张塔罗牌}
10.结果：{__单张塔罗牌}
"""
]
